// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type ArticlePageDocumentDataBodySlice = never;

/**
 * Item in *Article Page → References*
 */
export interface ArticlePageDocumentDataReferencesItem {
  /**
   * Location field in *Article Page → References*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Excerpt or note location
   * - **API ID Path**: article_page.references[].location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Reference text field in *Article Page → References*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.references[].reference_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  reference_text: prismic.RichTextField;
}

/**
 * Content for Article Page documents
 */
interface ArticlePageDocumentData {
  /**
   * Title field in *Article Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Article title
   * - **API ID Path**: article_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Meta title field in *Article Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO title
   * - **API ID Path**: article_page.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta description field in *Article Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_description: prismic.RichTextField;

  /**
   * Hero title field in *Article Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Display title
   * - **API ID Path**: article_page.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Hero subtitle field in *Article Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Byline or secondary title
   * - **API ID Path**: article_page.hero_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_subtitle: prismic.KeyTextField;

  /**
   * Hero image field in *Article Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Hero image credit field in *Article Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.hero_image_credit
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_image_credit: prismic.RichTextField;

  /**
   * Body field in *Article Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<ArticlePageDocumentDataBodySlice>;

  /**
   * References field in *Article Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.references[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  references: prismic.GroupField<
    Simplify<ArticlePageDocumentDataReferencesItem>
  >;

  /**
   * Works cited field in *Article Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.works_cited
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  works_cited: prismic.RichTextField; /**
   * Issue field in *Article Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.issue
   * - **Tab**: Relationships
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  issue: prismic.ContentRelationshipField;

  /**
   * Parent section field in *Article Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.parent_section
   * - **Tab**: Relationships
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  parent_section: prismic.ContentRelationshipField; /**
   * Hide from sitemap field in *Article Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article_page.hide_from_sitemap
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hide_from_sitemap: prismic.BooleanField;

  /**
   * Tile title field in *Article Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Card title
   * - **API ID Path**: article_page.tile_title
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tile_title: prismic.KeyTextField;

  /**
   * Tile summary field in *Article Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.tile_summary
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  tile_summary: prismic.RichTextField;

  /**
   * Tile thumbnail field in *Article Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_page.tile_thumbnail
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  tile_thumbnail: prismic.ImageField<never>;
}

/**
 * Article Page document from Prismic
 *
 * - **API ID**: `article_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ArticlePageDocumentData>,
    "article_page",
    Lang
  >;

type ContentPageDocumentDataBodySlice = never;

/**
 * Content for Content Page documents
 */
interface ContentPageDocumentData {
  /**
   * Title field in *Content Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page title
   * - **API ID Path**: content_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Meta title field in *Content Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO title
   * - **API ID Path**: content_page.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta description field in *Content Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_description: prismic.RichTextField;

  /**
   * Hero title field in *Content Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Display title
   * - **API ID Path**: content_page.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Hero subtitle field in *Content Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Secondary heading
   * - **API ID Path**: content_page.hero_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_subtitle: prismic.KeyTextField;

  /**
   * Hero image field in *Content Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Hero image credit field in *Content Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.hero_image_credit
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_image_credit: prismic.RichTextField;

  /**
   * Body field in *Content Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<ContentPageDocumentDataBodySlice>; /**
   * Issue field in *Content Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.issue
   * - **Tab**: Relationships
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  issue: prismic.ContentRelationshipField;

  /**
   * Parent page field in *Content Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.parent_page
   * - **Tab**: Relationships
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  parent_page: prismic.ContentRelationshipField; /**
   * Show in navigation field in *Content Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content_page.show_in_navigation
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_in_navigation: prismic.BooleanField;

  /**
   * Hide from sitemap field in *Content Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content_page.hide_from_sitemap
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hide_from_sitemap: prismic.BooleanField;

  /**
   * Tile title field in *Content Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Card title
   * - **API ID Path**: content_page.tile_title
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tile_title: prismic.KeyTextField;

  /**
   * Tile summary field in *Content Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.tile_summary
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  tile_summary: prismic.RichTextField;

  /**
   * Tile thumbnail field in *Content Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_page.tile_thumbnail
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  tile_thumbnail: prismic.ImageField<never>;
}

/**
 * Content Page document from Prismic
 *
 * - **API ID**: `content_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContentPageDocumentData>,
    "content_page",
    Lang
  >;

type IssuePageDocumentDataBodySlice = never;

/**
 * Content for Issue Page documents
 */
interface IssuePageDocumentData {
  /**
   * Title field in *Issue Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Issue title
   * - **API ID Path**: issue_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Issue number field in *Issue Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 20
   * - **API ID Path**: issue_page.issue_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  issue_number: prismic.NumberField;

  /**
   * Publication date field in *Issue Page*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_page.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publication_date: prismic.DateField;

  /**
   * Hero title field in *Issue Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_page.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Hero subtitle field in *Issue Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_page.hero_subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_subtitle: prismic.KeyTextField;

  /**
   * Hero image field in *Issue Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Hero image credit field in *Issue Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_page.hero_image_credit
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_image_credit: prismic.RichTextField;

  /**
   * Body field in *Issue Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<IssuePageDocumentDataBodySlice>; /**
   * Hide from sitemap field in *Issue Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: issue_page.hide_from_sitemap
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hide_from_sitemap: prismic.BooleanField;

  /**
   * Tile title field in *Issue Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_page.tile_title
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tile_title: prismic.KeyTextField;

  /**
   * Tile summary field in *Issue Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_page.tile_summary
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  tile_summary: prismic.RichTextField;

  /**
   * Tile thumbnail field in *Issue Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_page.tile_thumbnail
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  tile_thumbnail: prismic.ImageField<never>;
}

/**
 * Issue Page document from Prismic
 *
 * - **API ID**: `issue_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IssuePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<IssuePageDocumentData>,
    "issue_page",
    Lang
  >;

export type AllDocumentTypes =
  | ArticlePageDocument
  | ContentPageDocument
  | IssuePageDocument;

/**
 * Primary content in *BiographyList → Default → Primary*
 */
export interface BiographyListSliceDefaultPrimary {
  /**
   * Heading field in *BiographyList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: BiographyList.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *BiographyList → Items*
 */
export interface BiographyListSliceDefaultItem {
  /**
   * Name field in *BiographyList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contributor name
   * - **API ID Path**: BiographyList.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Summary field in *BiographyList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: BiographyList.items[].summary
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;

  /**
   * Image field in *BiographyList → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: BiographyList.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Linked article field in *BiographyList → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: BiographyList.items[].linked_article
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  linked_article: prismic.ContentRelationshipField;
}

/**
 * Default variation for BiographyList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Contributor biographies with optional related article
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BiographyListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BiographyListSliceDefaultPrimary>,
  Simplify<BiographyListSliceDefaultItem>
>;

/**
 * Slice variation for *BiographyList*
 */
type BiographyListSliceVariation = BiographyListSliceDefault;

/**
 * BiographyList Shared Slice
 *
 * - **API ID**: `BiographyList`
 * - **Description**: Contributor biographies with optional related article
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BiographyListSlice = prismic.SharedSlice<
  "BiographyList",
  BiographyListSliceVariation
>;

/**
 * Primary content in *ContributorList → Default → Primary*
 */
export interface ContributorListSliceDefaultPrimary {
  /**
   * Heading field in *ContributorList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: ContributorList.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *ContributorList → Items*
 */
export interface ContributorListSliceDefaultItem {
  /**
   * Title link field in *ContributorList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Primary linked title
   * - **API ID Path**: ContributorList.items[].title_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_link: prismic.KeyTextField;

  /**
   * Issue field in *ContributorList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Issue label
   * - **API ID Path**: ContributorList.items[].issue
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  issue: prismic.KeyTextField;

  /**
   * Thumbnail field in *ContributorList → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ContributorList.items[].thumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Body text field in *ContributorList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ContributorList.items[].body_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body_text: prismic.RichTextField;

  /**
   * Link label field in *ContributorList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional link label
   * - **API ID Path**: ContributorList.items[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;

  /**
   * Link field in *ContributorList → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ContributorList.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ContributorList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Issue contributor cards with metadata and links
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContributorListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContributorListSliceDefaultPrimary>,
  Simplify<ContributorListSliceDefaultItem>
>;

/**
 * Slice variation for *ContributorList*
 */
type ContributorListSliceVariation = ContributorListSliceDefault;

/**
 * ContributorList Shared Slice
 *
 * - **API ID**: `ContributorList`
 * - **Description**: Issue contributor cards with metadata and links
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContributorListSlice = prismic.SharedSlice<
  "ContributorList",
  ContributorListSliceVariation
>;

/**
 * Primary content in *FileLink → Default → Primary*
 */
export interface FileLinkSliceDefaultPrimary {
  /**
   * Title field in *FileLink → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: File title
   * - **API ID Path**: FileLink.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FileLink → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: FileLink.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * File field in *FileLink → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: FileLink.default.primary.file
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  file: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for FileLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Downloadable file or media link
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FileLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FileLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FileLink*
 */
type FileLinkSliceVariation = FileLinkSliceDefault;

/**
 * FileLink Shared Slice
 *
 * - **API ID**: `FileLink`
 * - **Description**: Downloadable file or media link
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FileLinkSlice = prismic.SharedSlice<
  "FileLink",
  FileLinkSliceVariation
>;

/**
 * Primary content in *FormEmbed → Default → Primary*
 */
export interface FormEmbedSliceDefaultPrimary {
  /**
   * Title field in *FormEmbed → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Form title
   * - **API ID Path**: FormEmbed.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Embed field in *FormEmbed → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: FormEmbed.default.primary.embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  embed: prismic.EmbedField;
}

/**
 * Default variation for FormEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Embedded form code
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormEmbedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormEmbedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormEmbed*
 */
type FormEmbedSliceVariation = FormEmbedSliceDefault;

/**
 * FormEmbed Shared Slice
 *
 * - **API ID**: `FormEmbed`
 * - **Description**: Embedded form code
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormEmbedSlice = prismic.SharedSlice<
  "FormEmbed",
  FormEmbedSliceVariation
>;

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * Heading field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Gallery heading
   * - **API ID Path**: Gallery.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
  /**
   * Image field in *Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Gallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Gallery.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Credit field in *Gallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Gallery.items[].credit
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  credit: prismic.RichTextField;

  /**
   * Anchor field in *Gallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional anchor id
   * - **API ID Path**: Gallery.items[].anchor
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor: prismic.KeyTextField;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  Simplify<GallerySliceDefaultItem>
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `Gallery`
 * - **Description**: Image gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySlice = prismic.SharedSlice<
  "Gallery",
  GallerySliceVariation
>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Image → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Image.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Credit field in *Image → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Image.default.primary.credit
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  credit: prismic.RichTextField;

  /**
   * Anchor field in *Image → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional anchor id
   * - **API ID Path**: Image.default.primary.anchor
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor: prismic.KeyTextField;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standalone image with caption and credit
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `Image`
 * - **Description**: Standalone image with caption and credit
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"Image", ImageSliceVariation>;

/**
 * Primary content in *LinkedTiles → Default → Primary*
 */
export interface LinkedTilesSliceDefaultPrimary {
  /**
   * Heading field in *LinkedTiles → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: LinkedTiles.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *LinkedTiles → Items*
 */
export interface LinkedTilesSliceDefaultItem {
  /**
   * Title field in *LinkedTiles → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tile title
   * - **API ID Path**: LinkedTiles.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Summary field in *LinkedTiles → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: LinkedTiles.items[].summary
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;

  /**
   * Link field in *LinkedTiles → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: LinkedTiles.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  link: prismic.ContentRelationshipField;

  /**
   * Image field in *LinkedTiles → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: LinkedTiles.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for LinkedTiles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Grid of linked internal documents
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LinkedTilesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkedTilesSliceDefaultPrimary>,
  Simplify<LinkedTilesSliceDefaultItem>
>;

/**
 * Slice variation for *LinkedTiles*
 */
type LinkedTilesSliceVariation = LinkedTilesSliceDefault;

/**
 * LinkedTiles Shared Slice
 *
 * - **API ID**: `LinkedTiles`
 * - **Description**: Grid of linked internal documents
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LinkedTilesSlice = prismic.SharedSlice<
  "LinkedTiles",
  LinkedTilesSliceVariation
>;

/**
 * Primary content in *Quote → Default → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * Quote field in *Quote → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Quote.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Attribution field in *Quote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Quote source
   * - **API ID Path**: Quote.default.primary.attribution
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  attribution: prismic.KeyTextField;

  /**
   * Centered field in *Quote → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: Quote.default.primary.centered
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  centered: prismic.BooleanField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Pull quote with optional attribution
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `Quote`
 * - **Description**: Pull quote with optional attribution
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteSlice = prismic.SharedSlice<"Quote", QuoteSliceVariation>;

/**
 * Primary content in *RichTextSection → Default → Primary*
 */
export interface RichTextSectionSliceDefaultPrimary {
  /**
   * Heading field in *RichTextSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section heading
   * - **API ID Path**: RichTextSection.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *RichTextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: RichTextSection.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for RichTextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Section heading and body copy
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichTextSection*
 */
type RichTextSectionSliceVariation = RichTextSectionSliceDefault;

/**
 * RichTextSection Shared Slice
 *
 * - **API ID**: `RichTextSection`
 * - **Description**: Section heading and body copy
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSectionSlice = prismic.SharedSlice<
  "RichTextSection",
  RichTextSectionSliceVariation
>;

/**
 * Primary content in *VideoEmbed → Default → Primary*
 */
export interface VideoEmbedSliceDefaultPrimary {
  /**
   * Embed URL field in *VideoEmbed → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://...
   * - **API ID Path**: VideoEmbed.default.primary.embed_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  embed_url: prismic.KeyTextField;

  /**
   * Caption field in *VideoEmbed → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: VideoEmbed.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Credit field in *VideoEmbed → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: VideoEmbed.default.primary.credit
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  credit: prismic.RichTextField;

  /**
   * Use in hero field in *VideoEmbed → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: VideoEmbed.default.primary.use_in_hero
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  use_in_hero: prismic.BooleanField;
}

/**
 * Default variation for VideoEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Embedded video with metadata
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoEmbedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoEmbedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoEmbed*
 */
type VideoEmbedSliceVariation = VideoEmbedSliceDefault;

/**
 * VideoEmbed Shared Slice
 *
 * - **API ID**: `VideoEmbed`
 * - **Description**: Embedded video with metadata
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoEmbedSlice = prismic.SharedSlice<
  "VideoEmbed",
  VideoEmbedSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticlePageDocument,
      ArticlePageDocumentData,
      ArticlePageDocumentDataBodySlice,
      ArticlePageDocumentDataReferencesItem,
      ContentPageDocument,
      ContentPageDocumentData,
      ContentPageDocumentDataBodySlice,
      IssuePageDocument,
      IssuePageDocumentData,
      IssuePageDocumentDataBodySlice,
      AllDocumentTypes,
      BiographyListSlice,
      BiographyListSliceDefaultPrimary,
      BiographyListSliceDefaultItem,
      BiographyListSliceVariation,
      BiographyListSliceDefault,
      ContributorListSlice,
      ContributorListSliceDefaultPrimary,
      ContributorListSliceDefaultItem,
      ContributorListSliceVariation,
      ContributorListSliceDefault,
      FileLinkSlice,
      FileLinkSliceDefaultPrimary,
      FileLinkSliceVariation,
      FileLinkSliceDefault,
      FormEmbedSlice,
      FormEmbedSliceDefaultPrimary,
      FormEmbedSliceVariation,
      FormEmbedSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimary,
      GallerySliceDefaultItem,
      GallerySliceVariation,
      GallerySliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      LinkedTilesSlice,
      LinkedTilesSliceDefaultPrimary,
      LinkedTilesSliceDefaultItem,
      LinkedTilesSliceVariation,
      LinkedTilesSliceDefault,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      RichTextSectionSlice,
      RichTextSectionSliceDefaultPrimary,
      RichTextSectionSliceVariation,
      RichTextSectionSliceDefault,
      VideoEmbedSlice,
      VideoEmbedSliceDefaultPrimary,
      VideoEmbedSliceVariation,
      VideoEmbedSliceDefault,
    };
  }
}
