// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  BiographyList: dynamic(() => import("./BiographyList")),
  ContributorList: dynamic(() => import("./ContributorList")),
  FileLink: dynamic(() => import("./FileLink")),
  FormEmbed: dynamic(() => import("./FormEmbed")),
  Gallery: dynamic(() => import("./Gallery")),
  Image: dynamic(() => import("./Image")),
  LinkedTiles: dynamic(() => import("./LinkedTiles")),
  Quote: dynamic(() => import("./Quote")),
  RichTextSection: dynamic(() => import("./RichTextSection")),
  VideoEmbed: dynamic(() => import("./VideoEmbed")),
};
